<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php';simceSecurityHeaders();
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')simceJson(array('ok'=>false,'error'=>'Método no permitido.'),405);
$d=simceReadJson(65536);$action=(string)($d['action']??'login');
if($action==='logout'){simceRequireAdmin();simceRequireCsrf();simceDestroySession();simceJson(array('ok'=>true));}
if($action!=='login')simceJson(array('ok'=>false,'error'=>'Acción no válida.'),400);
$db=simceDatabase();if((int)$db->query('SELECT COUNT(*) FROM administradores WHERE activo=1')->fetchColumn()===0)simceJson(array('ok'=>false,'needsSetup'=>true,'error'=>'Primero crea el superadministrador de la plataforma.'),503);
$user=trim((string)($d['usuario']??''));$password=(string)($d['password']??'');$schoolCode=strtolower(trim((string)($d['colegio']??'')));$school=false;
if($schoolCode!==''){$school=simceSchoolByCode($db,$schoolCode);if(!$school)simceJson(array('ok'=>false,'error'=>'Código de colegio, usuario o contraseña incorrectos.'),401);$s=$db->prepare("SELECT id,usuario,password_hash,rol,colegio_id FROM administradores WHERE colegio_id=:c AND usuario=:u AND activo=1 AND rol IN('colegio_admin','docente')");$s->execute(array(':c'=>$school['id'],':u'=>$user));}
else{$s=$db->prepare("SELECT id,usuario,password_hash,rol,colegio_id FROM administradores WHERE colegio_id IS NULL AND usuario=:u AND activo=1 AND rol='plataforma_superadmin'");$s->execute(array(':u'=>$user));}
$admin=$s->fetch();$context=$schoolCode?:'plataforma';$ip=simceClientIp();$now=time();$a=$db->prepare('SELECT intentos,bloqueado_hasta FROM intentos_login WHERE ip=:ip AND contexto=:ctx');$a->execute(array(':ip'=>$ip,':ctx'=>$context));$attempt=$a->fetch();if($attempt&&(int)$attempt['bloqueado_hasta']>$now)simceJson(array('ok'=>false,'error'=>'Demasiados intentos. Intenta más tarde.'),429);
if(!$admin||!password_verify($password,(string)$admin['password_hash'])){$failed=$attempt?(int)$attempt['intentos']+1:1;$until=$failed>=5?$now+900:0;if($attempt){$q=$db->prepare('UPDATE intentos_login SET intentos=:n,bloqueado_hasta=:b,actualizado_en=:t WHERE ip=:ip AND contexto=:ctx');}else{$q=$db->prepare('INSERT INTO intentos_login(intentos,bloqueado_hasta,actualizado_en,ip,contexto)VALUES(:n,:b,:t,:ip,:ctx)');}$q->execute(array(':n'=>$failed,':b'=>$until,':t'=>$now,':ip'=>$ip,':ctx'=>$context));usleep(350000);simceJson(array('ok'=>false,'error'=>'Código de colegio, usuario o contraseña incorrectos.'),401);}
$db->prepare('DELETE FROM intentos_login WHERE ip=:ip AND contexto=:ctx')->execute(array(':ip'=>$ip,':ctx'=>$context));$db->prepare('UPDATE administradores SET last_login_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(array(':id'=>$admin['id']));
simceStartSession();session_regenerate_id(true);$_SESSION['admin_id']=(int)$admin['id'];$_SESSION['admin_usuario']=$admin['usuario'];$_SESSION['admin_rol']=$admin['rol'];$_SESSION['colegio_id']=$admin['colegio_id']===null?0:(int)$admin['colegio_id'];$_SESSION['admin_password_stamp']=hash('sha256',$admin['password_hash']);$_SESSION['csrf_token']=bin2hex(random_bytes(32));$_SESSION['last_activity']=time();simceJson(array('ok'=>true,'redirect'=>$admin['rol']==='plataforma_superadmin'?'plataforma.php':'pruebas_educativas.php','csrfToken'=>$_SESSION['csrf_token']));

