<?php
declare(strict_types=1);
const SIMCE_VERSION='2.1.0';
function simceDatabase():PDO{static $db=null;if($db instanceof PDO)return $db;$dsn=trim((string)getenv('SIMCE_DB_DSN'));$u=(string)getenv('SIMCE_DB_USER');$p=(string)getenv('SIMCE_DB_PASSWORD');if($dsn===''){$path=trim((string)getenv('SIMCE_DATABASE_PATH'))?:__DIR__.'/data/simce_v21.sqlite';if(!is_dir(dirname($path)))mkdir(dirname($path),0770,true);$dsn='sqlite:'.$path;}try{$db=new PDO($dsn,$u,$p,array(PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false));}catch(PDOException $e){throw new RuntimeException('No se pudo conectar a la base de datos v2.1.0.');}if(simceDbDriver($db)==='sqlite'){$db->exec('PRAGMA foreign_keys=ON');$db->exec('PRAGMA busy_timeout=5000');}else{$db->exec('SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci');}simceInitializeSchema($db);return $db;}
function simceDbDriver(PDO $db):string{return(string)$db->getAttribute(PDO::ATTR_DRIVER_NAME);}
function simceInitializeSchema(PDO $db):void{$my=simceDbDriver($db)==='mysql';$id=$my?'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY':'INTEGER PRIMARY KEY AUTOINCREMENT';$b=$my?'TINYINT(1)':'INTEGER';$e=$my?' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci':'';
$db->exec("CREATE TABLE IF NOT EXISTS colegios(id $id,codigo VARCHAR(40) NOT NULL UNIQUE,nombre VARCHAR(150) NOT NULL,activo $b NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)$e");
$db->exec("CREATE TABLE IF NOT EXISTS administradores(id $id,colegio_id BIGINT NULL,usuario VARCHAR(50) NOT NULL,password_hash VARCHAR(255) NOT NULL,rol VARCHAR(30) NOT NULL,activo $b NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,last_login_at TIMESTAMP NULL,UNIQUE(colegio_id,usuario))$e");
$db->exec("CREATE TABLE IF NOT EXISTS intentos_login(ip VARCHAR(64) NOT NULL,contexto VARCHAR(80) NOT NULL,intentos INTEGER DEFAULT 0,bloqueado_hasta BIGINT DEFAULT 0,actualizado_en BIGINT NOT NULL,PRIMARY KEY(ip,contexto))$e");
$db->exec("CREATE TABLE IF NOT EXISTS alumnos(id $id,colegio_id BIGINT NOT NULL,public_id VARCHAR(40) NOT NULL UNIQUE,rut VARCHAR(40) NOT NULL,rut_normalizado VARCHAR(40) NOT NULL,nombre VARCHAR(150) NOT NULL,curso VARCHAR(80) NOT NULL,idgrado INTEGER NOT NULL,nivel VARCHAR(10) NOT NULL,activo $b DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(colegio_id,rut_normalizado))$e");
$db->exec("CREATE TABLE IF NOT EXISTS cursos(id $id,colegio_id BIGINT NOT NULL,nombre VARCHAR(80) NOT NULL,idgrado INTEGER NOT NULL,nivel VARCHAR(10) NOT NULL,pin_hash VARCHAR(255) NULL,requiere_pin $b DEFAULT 1,activo $b DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(colegio_id,nombre))$e");
$db->exec("CREATE TABLE IF NOT EXISTS pruebas(id $id,colegio_id BIGINT NOT NULL,ruta VARCHAR(500) NOT NULL,titulo VARCHAR(200) NOT NULL,curso_codigo VARCHAR(30) NOT NULL,asignatura VARCHAR(60) NOT NULL,creador_id BIGINT NULL,activa $b DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(colegio_id,ruta))$e");
$db->exec("CREATE TABLE IF NOT EXISTS asignaciones(id $id,colegio_id BIGINT NOT NULL,prueba_id BIGINT NOT NULL,curso_id BIGINT NOT NULL,activa $b DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(prueba_id,curso_id))$e");
$db->exec("CREATE TABLE IF NOT EXISTS resultados(id $id,colegio_id BIGINT NOT NULL,alumno_id BIGINT NOT NULL,prueba_id BIGINT NOT NULL,intento INTEGER DEFAULT 1,correctas INTEGER NOT NULL,total INTEGER NOT NULL,puntaje DECIMAL(10,2) NOT NULL,puntaje_max DECIMAL(10,2) NOT NULL,porcentaje DECIMAL(6,2) NOT NULL,nota DECIMAL(4,2) NULL,respuestas_json TEXT NOT NULL,iniciado_at TIMESTAMP NULL,finalizado_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,ip VARCHAR(64) DEFAULT '',UNIQUE(alumno_id,prueba_id,intento))$e");
$db->exec("CREATE TABLE IF NOT EXISTS importaciones_alumnos(id $id,colegio_id BIGINT NOT NULL,archivo VARCHAR(200) NOT NULL,total INTEGER NOT NULL,insertados INTEGER NOT NULL,actualizados INTEGER NOT NULL,rechazados INTEGER NOT NULL,administrador_id BIGINT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)$e");
$db->exec("CREATE TABLE IF NOT EXISTS auditoria_administracion(id $id,colegio_id BIGINT NULL,accion VARCHAR(80) NOT NULL,detalle TEXT NOT NULL,administrador_id BIGINT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)$e");
$db->exec("CREATE TABLE IF NOT EXISTS configuracion(colegio_id BIGINT NOT NULL,clave VARCHAR(80) NOT NULL,valor TEXT NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(colegio_id,clave))$e");}
function simceTenantId():int{return(int)($_SESSION['colegio_id']??0);}
function simceSchoolByCode(PDO $db,string $code){$s=$db->prepare('SELECT id,codigo,nombre FROM colegios WHERE codigo=:c AND activo=1');$s->execute(array(':c'=>strtolower(trim($code))));return$s->fetch();}
function simceSyncCourses(PDO $db,?int $cid=null):void{$cid=$cid?:simceTenantId();if($cid<1)return;$s=$db->prepare('SELECT curso,idgrado,nivel FROM alumnos WHERE colegio_id=:c AND activo=1 GROUP BY curso,idgrado,nivel');$s->execute(array(':c'=>$cid));foreach($s->fetchAll()as$r){$q=$db->prepare('SELECT id FROM cursos WHERE colegio_id=:c AND nombre=:n');$q->execute(array(':c'=>$cid,':n'=>$r['curso']));if(!$q->fetch()){$i=$db->prepare('INSERT INTO cursos(colegio_id,nombre,idgrado,nivel)VALUES(:c,:n,:g,:l)');$i->execute(array(':c'=>$cid,':n'=>$r['curso'],':g'=>$r['idgrado'],':l'=>$r['nivel']));}}}
function simceBranding(PDO $db,?int $cid=null):array{$v=array('nombre_plataforma'=>'Pruebas Educativas','nombre_establecimiento'=>'Plataforma SIMCE','subtitulo'=>'Plataforma Evaluativa','saludo'=>'Hola, bienvenido al sistema','seleccion_perfil'=>'Selecciona tu perfil','logo'=>'logo_carlos_miranda.jpg');$cid=$cid?:simceTenantId();if($cid>0){$s=$db->prepare("SELECT clave,valor FROM configuracion WHERE colegio_id=:c AND clave LIKE 'marca_%'");$s->execute(array(':c'=>$cid));foreach($s->fetchAll()as$r){$k=substr((string)$r['clave'],6);if(array_key_exists($k,$v))$v[$k]=(string)$r['valor'];}}return$v;}
function simceCourseCodeMatches(string$n,string$c):bool{$t=strtolower(strtr($n,array('á'=>'a','é'=>'e','í'=>'i','ó'=>'o','ú'=>'u','°'=>'','º'=>'')));return preg_match('/([1-8])\s*(basico|medio)/',$t,$m)===1&&$c===$m[1].($m[2]==='basico'?'basico':'medio');}
function simceSyncStoredTests(PDO$db,?int$cid=null):void{$cid=$cid?:simceTenantId();if($cid<1)return;$root=__DIR__.'/pruebas';if(!is_dir($root))return;foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS))as$f){if(!$f->isFile()||strtolower($f->getExtension())!=='html')continue;$r=str_replace('\\','/',substr($f->getPathname(),strlen(__DIR__)+1));$p=explode('/',$r);if(count($p)<4)continue;$q=$db->prepare('SELECT id FROM pruebas WHERE colegio_id=:c AND ruta=:r');$q->execute(array(':c'=>$cid,':r'=>$r));$tid=$q->fetchColumn();if(!$tid){$i=$db->prepare('INSERT INTO pruebas(colegio_id,ruta,titulo,curso_codigo,asignatura)VALUES(:c,:r,:t,:cc,:a)');$i->execute(array(':c'=>$cid,':r'=>$r,':t'=>str_replace(array('_','-'),' ',pathinfo($f->getFilename(),PATHINFO_FILENAME)),':cc'=>$p[1],':a'=>$p[2]));$tid=(int)$db->lastInsertId();}$cs=$db->prepare('SELECT id,nombre FROM cursos WHERE colegio_id=:c AND activo=1');$cs->execute(array(':c'=>$cid));foreach($cs->fetchAll()as$course)if(simceCourseCodeMatches($course['nombre'],$p[1])){$x=$db->prepare('SELECT id FROM asignaciones WHERE colegio_id=:c AND prueba_id=:p AND curso_id=:u');$x->execute(array(':c'=>$cid,':p'=>$tid,':u'=>$course['id']));if(!$x->fetch()){$a=$db->prepare('INSERT INTO asignaciones(colegio_id,prueba_id,curso_id)VALUES(:c,:p,:u)');$a->execute(array(':c'=>$cid,':p'=>$tid,':u'=>$course['id']));}}}}
function simceJson(array$p,int$s=200):void{http_response_code($s);header('Content-Type:application/json;charset=utf-8');header('Cache-Control:no-store');echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function simceReadJson(int$m=15728640):array{$r=file_get_contents('php://input');if($r===false||strlen($r)>$m)simceJson(array('ok'=>false,'error'=>'Solicitud inválida.'),400);$d=json_decode($r,true);if(!is_array($d))simceJson(array('ok'=>false,'error'=>'JSON inválido.'),400);return$d;}
function simceClientIp():string{return substr((string)($_SERVER['REMOTE_ADDR']??'unknown'),0,64);}

