<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php';simceRequireRole(array('colegio_admin','docente'));$db=simceDatabase();$cid=simceTenantId();if($cid<1)simceJson(array('ok'=>false,'error'=>'Sesión sin colegio.'),403);
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){simceSyncCourses($db,$cid);simceSyncStoredTests($db,$cid);$s=$db->prepare("SELECT id,nombre,idgrado,nivel,CASE WHEN pin_hash IS NULL OR pin_hash='' THEN 0 ELSE 1 END pin_configurado,requiere_pin FROM cursos WHERE colegio_id=:c AND activo=1 ORDER BY idgrado,nombre");$s->execute(array(':c'=>$cid));$r=$db->prepare('SELECT r.id,a.nombre,a.curso,p.titulo,p.asignatura,r.intento,r.correctas,r.total,r.porcentaje,r.nota,r.finalizado_at FROM resultados r JOIN alumnos a ON a.id=r.alumno_id AND a.colegio_id=r.colegio_id JOIN pruebas p ON p.id=r.prueba_id AND p.colegio_id=r.colegio_id WHERE r.colegio_id=:c ORDER BY r.finalizado_at DESC LIMIT 500');$r->execute(array(':c'=>$cid));$users=array();if($_SESSION['admin_rol']==='colegio_admin'){$u=$db->prepare("SELECT id,usuario,rol,activo,created_at,last_login_at FROM administradores WHERE colegio_id=:c AND rol='docente' ORDER BY usuario");$u->execute(array(':c'=>$cid));$users=$u->fetchAll();}$school=$db->prepare('SELECT codigo,nombre FROM colegios WHERE id=:c');$school->execute(array(':c'=>$cid));simceJson(array('ok'=>true,'rol'=>$_SESSION['admin_rol'],'colegio'=>$school->fetch(),'cursos'=>$s->fetchAll(),'resultados'=>$r->fetchAll(),'usuarios'=>$users,'version'=>SIMCE_VERSION));}
simceRequireCsrf();$d=simceReadJson(65536);$a=(string)($d['action']??'');
if($a==='course_pin'||$a==='clear_course_pin'){simceRequireRole(array('colegio_admin','docente'));$id=(int)($d['curso']??0);if($a==='course_pin'){$pin=trim((string)($d['pin']??''));if(strlen($pin)<4||strlen($pin)>30)simceJson(array('ok'=>false,'error'=>'PIN de 4 a 30 caracteres.'),400);$s=$db->prepare('UPDATE cursos SET pin_hash=:p,requiere_pin=1,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND colegio_id=:c');$s->execute(array(':p'=>password_hash($pin,PASSWORD_DEFAULT),':id'=>$id,':c'=>$cid));}else{$s=$db->prepare('UPDATE cursos SET pin_hash=NULL,requiere_pin=0,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND colegio_id=:c');$s->execute(array(':id'=>$id,':c'=>$cid));}if($s->rowCount()!==1)simceJson(array('ok'=>false,'error'=>'Curso no encontrado.'),404);simceJson(array('ok'=>true));}
if($a==='create_teacher'){simceRequireRole(array('colegio_admin'));$u=trim((string)($d['usuario']??''));$p=(string)($d['password']??'');if(!preg_match('/^[A-Za-z0-9._-]{3,50}$/',$u)||strlen($p)<12||!preg_match('/[A-Z]/',$p)||!preg_match('/[a-z]/',$p)||!preg_match('/[0-9]/',$p))simceJson(array('ok'=>false,'error'=>'Usuario o contraseña no válidos.'),400);try{$s=$db->prepare("INSERT INTO administradores(colegio_id,usuario,password_hash,rol)VALUES(:c,:u,:p,'docente')");$s->execute(array(':c'=>$cid,':u'=>$u,':p'=>password_hash($p,PASSWORD_DEFAULT)));}catch(Throwable$e){simceJson(array('ok'=>false,'error'=>'El docente ya existe.'),409);}simceJson(array('ok'=>true));}
if($a==='reset_teacher'){simceRequireRole(array('colegio_admin'));$id=(int)($d['id']??0);$p=(string)($d['password']??'');if(strlen($p)<12||!preg_match('/[A-Z]/',$p)||!preg_match('/[a-z]/',$p)||!preg_match('/[0-9]/',$p))simceJson(array('ok'=>false,'error'=>'La contraseña debe tener al menos 12 caracteres, mayúscula, minúscula y número.'),400);$s=$db->prepare("UPDATE administradores SET password_hash=:p WHERE id=:id AND colegio_id=:c AND rol='docente'");$s->execute(array(':p'=>password_hash($p,PASSWORD_DEFAULT),':id'=>$id,':c'=>$cid));if($s->rowCount()!==1)simceJson(array('ok'=>false,'error'=>'Usuario no encontrado.'),404);simceJson(array('ok'=>true));}
if($a==='set_teacher_status'){simceRequireRole(array('colegio_admin'));$id=(int)($d['id']??0);$active=!empty($d['activo'])?1:0;$s=$db->prepare("UPDATE administradores SET activo=:activo WHERE id=:id AND colegio_id=:c AND rol='docente'");$s->execute(array(':activo'=>$active,':id'=>$id,':c'=>$cid));if($s->rowCount()!==1)simceJson(array('ok'=>false,'error'=>'Usuario no encontrado o ya estaba en ese estado.'),404);$log=$db->prepare('INSERT INTO auditoria_administracion(colegio_id,accion,detalle,administrador_id)VALUES(:c,:a,:d,:admin)');$log->execute(array(':c'=>$cid,':a'=>$active?'activar_docente':'desactivar_docente',':d'=>'Usuario docente ID '.$id,':admin'=>(int)$_SESSION['admin_id']));simceJson(array('ok'=>true));}
if($a==='delete_teacher'){simceRequireRole(array('colegio_admin'));$id=(int)($d['id']??0);$find=$db->prepare("SELECT usuario FROM administradores WHERE id=:id AND colegio_id=:c AND rol='docente'");$find->execute(array(':id'=>$id,':c'=>$cid));$teacher=$find->fetch();if(!$teacher)simceJson(array('ok'=>false,'error'=>'Usuario no encontrado.'),404);try{$db->beginTransaction();$delete=$db->prepare("DELETE FROM administradores WHERE id=:id AND colegio_id=:c AND rol='docente'");$delete->execute(array(':id'=>$id,':c'=>$cid));$log=$db->prepare('INSERT INTO auditoria_administracion(colegio_id,accion,detalle,administrador_id)VALUES(:c,:a,:d,:admin)');$log->execute(array(':c'=>$cid,':a'=>'eliminar_docente',':d'=>'Usuario docente eliminado: '.$teacher['usuario'],':admin'=>(int)$_SESSION['admin_id']));$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();simceJson(array('ok'=>false,'error'=>'No se pudo eliminar el usuario.'),409);}simceJson(array('ok'=>true));}
simceJson(array('ok'=>false,'error'=>'Acción no válida.'),400);
