<?php require_once __DIR__.'/seguridad.php'; simceRequireAdmin(false); ?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administración SIMCE</title><style>
body{font-family:Arial,sans-serif;background:#f1f5f9;color:#172554;margin:0;padding:24px}main{max-width:1100px;margin:auto}section{background:#fff;padding:22px;border-radius:16px;margin:18px 0;box-shadow:0 8px 25px #0f172a12}input,select,button{padding:10px;border:1px solid #94a3b8;border-radius:8px;margin:4px}button{background:#1d4ed8;color:white;border:0;font-weight:700;cursor:pointer}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #e2e8f0}.scroll{overflow:auto}.msg{font-weight:700;margin:10px}a{color:#1d4ed8}</style></head><body><main><p><a href="pruebas_educativas.php">← Volver al panel docente</a></p><h1>Administración y resultados</h1><div id="msg" class="msg"></div>
<section id="courses"><h2>PIN común por curso</h2><p>El PIN actual no se puede recuperar porque se almacena de forma segura. Puedes definir uno nuevo o dejar el curso sin PIN.</p><div id="courseRows"></div></section>
<section id="users"><h2>Usuarios y perfiles</h2><div><input id="u" placeholder="Usuario"><input id="p" type="password" placeholder="Contraseña segura"><select id="role"><option value="docente">Docente</option><option value="administrador">Administrador</option><option value="superadmin">Superadmin</option></select><button id="create">Crear usuario</button></div><div id="userRows" class="scroll"></div></section>
<section><h2>Resultados identificados</h2><div id="results" class="scroll"></div></section></main><script src="sesion-cliente.js"></script><script>
let token='',role='';const msg=t=>document.querySelector('#msg').textContent=t;async function call(body){const r=await window.simceAuthenticatedFetch('gestion_api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return r.json()}
async function load(){const ses=await fetch('sesion.php').then(r=>r.json());token=ses.csrfToken;const x=await fetch('gestion_api.php?action=summary').then(r=>r.json());role=x.rol;if(role==='docente'){document.querySelector('#courses').style.display='none';document.querySelector('#users').style.display='none'}else document.querySelector('#courseRows').innerHTML=x.cursos.map(c=>`<div>${c.nombre} — ${c.pin_configurado?'PIN configurado':'SIN PIN'} <input type="text" id="pin${c.id}" placeholder="Nuevo PIN"><button onclick="pin(${c.id})">Guardar PIN</button><button onclick="clearPin(${c.id})" style="background:#64748b">Dejar sin PIN</button></div>`).join('');if(role==='superadmin')document.querySelector('#userRows').innerHTML='<table><tr><th>Usuario</th><th>Perfil</th><th>Activo</th><th>Contraseña</th></tr>'+x.usuarios.map(u=>`<tr><td>${esc(u.usuario)}</td><td>${u.rol}</td><td>${u.activo?'Sí':'No'}</td><td><input type="password" id="pw${u.id}" placeholder="Nueva contraseña"><button onclick="reset(${u.id})">Restablecer</button></td></tr>`).join('')+'</table>';else document.querySelector('#users').style.display='none';document.querySelector('#results').innerHTML='<table><tr><th>Estudiante</th><th>Curso</th><th>Asignatura / prueba</th><th>Resultado</th><th>Nota</th><th>Fecha</th></tr>'+x.resultados.map(r=>`<tr><td>${esc(r.nombre)}</td><td>${esc(r.curso)}</td><td>${esc(r.asignatura)} / ${esc(r.titulo)}</td><td>${r.correctas}/${r.total} (${r.porcentaje}%)</td><td>${r.nota??'—'}</td><td>${r.finalizado_at}</td></tr>`).join('')+'</table>'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function pin(id){const x=await call({action:'course_pin',curso:id,pin:document.querySelector('#pin'+id).value});msg(x.ok?'PIN actualizado.':x.error);if(x.ok)load()}async function clearPin(id){if(!confirm('¿Dejar este curso sin PIN? Cualquier persona que seleccione un estudiante del curso podrá ingresar.'))return;const x=await call({action:'clear_course_pin',curso:id});msg(x.ok?'El curso quedó sin PIN.':x.error);if(x.ok)load()}async function reset(id){const x=await call({action:'reset_password',id,password:document.querySelector('#pw'+id).value});msg(x.ok?'Contraseña actualizada; las sesiones anteriores fueron invalidadas.':x.error)}document.querySelector('#create').onclick=async()=>{const x=await call({action:'create_user',usuario:u.value,password:p.value,rol:document.querySelector('#role').value});msg(x.ok?'Usuario creado.':x.error);if(x.ok)load()};load();
</script></body></html>
