<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php'; simceJson(array('ok'=>false,'error'=>'Módulo anterior deshabilitado. Usa gestion_v21.php.'),410);
if($method==='GET' && $action==='summary') {
    simceSyncCourses($db); simceSyncStoredTests($db); $courses=$db->query("SELECT id,nombre,idgrado,nivel,(CASE WHEN pin_hash IS NULL OR pin_hash='' THEN 0 ELSE 1 END) AS pin_configurado,requiere_pin FROM cursos WHERE activo=1 ORDER BY idgrado,nombre")->fetchAll();
    $results=$db->query('SELECT r.id,a.nombre,a.curso,p.titulo,p.asignatura,r.intento,r.correctas,r.total,r.porcentaje,r.nota,r.finalizado_at FROM resultados r JOIN alumnos a ON a.id=r.alumno_id JOIN pruebas p ON p.id=r.prueba_id ORDER BY r.finalizado_at DESC LIMIT 500')->fetchAll();
    $users=array(); if(($_SESSION['admin_rol']??'')==='superadmin')$users=$db->query('SELECT id,usuario,rol,activo,created_at,last_login_at FROM administradores ORDER BY usuario')->fetchAll();
    simceJson(array('ok'=>true,'rol'=>$_SESSION['admin_rol'],'cursos'=>$courses,'resultados'=>$results,'usuarios'=>$users));
}
if($method!=='POST')simceJson(array('ok'=>false,'error'=>'Solicitud no válida.'),405); simceRequireCsrf(); $d=simceReadJson(65536); $action=(string)($d['action']??'');
if($action==='course_pin') { simceRequireRole(array('superadmin','administrador')); $id=(int)($d['curso']??0); $pin=trim((string)($d['pin']??'')); if(strlen($pin)<4||strlen($pin)>30)simceJson(array('ok'=>false,'error'=>'El PIN debe tener entre 4 y 30 caracteres.'),400); $s=$db->prepare('UPDATE cursos SET pin_hash=:h,requiere_pin=1,updated_at=CURRENT_TIMESTAMP WHERE id=:id');$s->execute(array(':h'=>password_hash($pin,PASSWORD_DEFAULT),':id'=>$id));simceJson(array('ok'=>true)); }
if($action==='clear_course_pin') { simceRequireRole(array('superadmin','administrador')); $id=(int)($d['curso']??0); if($id<1)simceJson(array('ok'=>false,'error'=>'Curso no válido.'),400); $check=$db->prepare('SELECT id FROM cursos WHERE id=:id');$check->execute(array(':id'=>$id));if(!$check->fetch())simceJson(array('ok'=>false,'error'=>'No se encontró el curso.'),404);$s=$db->prepare('UPDATE cursos SET pin_hash=NULL,requiere_pin=0,updated_at=CURRENT_TIMESTAMP WHERE id=:id');$s->execute(array(':id'=>$id));simceJson(array('ok'=>true)); }
if($action==='create_user') { simceRequireRole(array('superadmin')); $u=trim((string)($d['usuario']??''));$p=(string)($d['password']??'');$role=(string)($d['rol']??'docente');if(!preg_match('/^[A-Za-z0-9._-]{3,50}$/',$u)||strlen($p)<12||!preg_match('/[A-Z]/',$p)||!preg_match('/[a-z]/',$p)||!preg_match('/[0-9]/',$p)||!in_array($role,array('docente','administrador','superadmin'),true))simceJson(array('ok'=>false,'error'=>'Revisa usuario, perfil y contraseña (12 caracteres, mayúscula, minúscula y número).'),400);try{$s=$db->prepare('INSERT INTO administradores(usuario,password_hash,rol) VALUES(:u,:p,:r)');$s->execute(array(':u'=>$u,':p'=>password_hash($p,PASSWORD_DEFAULT),':r'=>$role));}catch(Throwable $e){simceJson(array('ok'=>false,'error'=>'El usuario ya existe o no se pudo crear.'),409);}simceJson(array('ok'=>true)); }
if($action==='reset_password') { simceRequireRole(array('superadmin'));$id=(int)($d['id']??0);$p=(string)($d['password']??'');if(strlen($p)<12||!preg_match('/[A-Z]/',$p)||!preg_match('/[a-z]/',$p)||!preg_match('/[0-9]/',$p))simceJson(array('ok'=>false,'error'=>'La contraseña no cumple los requisitos.'),400);$s=$db->prepare('UPDATE administradores SET password_hash=:p WHERE id=:id');$s->execute(array(':p'=>password_hash($p,PASSWORD_DEFAULT),':id'=>$id));simceJson(array('ok'=>true)); }
simceJson(array('ok'=>false,'error'=>'Acción no válida.'),400);
