<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php';simceSecurityHeaders();$db=simceDatabase();
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){simceStartSession();$cid=simceTenantId();if($cid<1&&isset($_GET['colegio'])){$school=simceSchoolByCode($db,(string)$_GET['colegio']);$cid=$school?(int)$school['id']:0;}simceJson(array('ok'=>true,'marca'=>simceBranding($db,$cid),'version'=>SIMCE_VERSION));}
simceRequireRole(array('plataforma_superadmin','colegio_admin'));simceRequireCsrf();$cid=simceTenantId();if(($_SESSION['admin_rol']??'')==='plataforma_superadmin'){$school=simceSchoolByCode($db,(string)($_POST['colegio']??''));$cid=$school?(int)$school['id']:0;}if($cid<1)simceJson(array('ok'=>false,'error'=>'Selecciona un colegio válido.'),403);
$fields=array('nombre_plataforma'=>80,'nombre_establecimiento'=>120,'subtitulo'=>120,'saludo'=>120,'seleccion_perfil'=>100);
foreach($fields as$key=>$max){$v=trim((string)($_POST[$key]??''));if($v===''||strlen($v)>$max)simceJson(array('ok'=>false,'error'=>'Revisa '.$key),400);$q=$db->prepare('SELECT clave FROM configuracion WHERE colegio_id=:c AND clave=:k');$q->execute(array(':c'=>$cid,':k'=>'marca_'.$key));$s=$q->fetch()?$db->prepare('UPDATE configuracion SET valor=:v,updated_at=CURRENT_TIMESTAMP WHERE colegio_id=:c AND clave=:k'):$db->prepare('INSERT INTO configuracion(colegio_id,clave,valor)VALUES(:c,:k,:v)');$s->execute(array(':c'=>$cid,':k'=>'marca_'.$key,':v'=>$v));}
function saveBrandFile(PDO$db,int$cid,string$field,string$key,array$allowed,int$max):void{if(!isset($_FILES[$field])||($_FILES[$field]['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return;$f=$_FILES[$field];if(($f['error']??1)!==UPLOAD_ERR_OK||($f['size']??0)>$max)simceJson(array('ok'=>false,'error'=>'El archivo '.$field.' no pudo subirse o supera el máximo.'),400);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!isset($allowed[$mime]))simceJson(array('ok'=>false,'error'=>'Formato no permitido para '.$field.'.'),400);$dir=__DIR__.'/uploads/marca/'.$cid;if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))simceJson(array('ok'=>false,'error'=>'No se pudo crear la carpeta de personalización.'),500);$relative='uploads/marca/'.$cid.'/'.$key.'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],__DIR__.'/'.$relative))simceJson(array('ok'=>false,'error'=>'No se pudo guardar '.$field.'.'),500);foreach(glob($dir.'/'.$key.'.*')?:array()as$old)if(realpath($old)!==realpath(__DIR__.'/'.$relative))@unlink($old);$q=$db->prepare('SELECT clave FROM configuracion WHERE colegio_id=:c AND clave=:k');$q->execute(array(':c'=>$cid,':k'=>'marca_'.$key));$s=$q->fetch()?$db->prepare('UPDATE configuracion SET valor=:v,updated_at=CURRENT_TIMESTAMP WHERE colegio_id=:c AND clave=:k'):$db->prepare('INSERT INTO configuracion(colegio_id,clave,valor)VALUES(:c,:k,:v)');$s->execute(array(':c'=>$cid,':k'=>'marca_'.$key,':v'=>$relative));}
saveBrandFile($db,$cid,'logo','logo',array('image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp'),2097152);saveBrandFile($db,$cid,'favicon','favicon',array('image/png'=>'png','image/x-icon'=>'ico','image/vnd.microsoft.icon'=>'ico'),524288);simceJson(array('ok'=>true,'marca'=>simceBranding($db,$cid),'version'=>SIMCE_VERSION));
