<?php require_once __DIR__.'/seguridad.php';simceRequireRole(array('plataforma_superadmin'),false);?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administración de colegios</title><style>
*{box-sizing:border-box}body{font-family:Inter,Arial,sans-serif;background:#f1f5f9;color:#172554;padding:24px;margin:0}main{max-width:1250px;margin:auto}section{background:#fff;padding:24px;border-radius:16px;margin:18px 0}input,button,a.action{padding:10px;border:1px solid #94a3b8;border-radius:8px;font:inherit}button,a.action{background:#1d4ed8;color:#fff;border:0;font-weight:700;text-decoration:none;display:inline-block;cursor:pointer}.secondary{background:#475569!important}.danger{background:#b91c1c!important}.success{background:#15803d!important}.create{display:grid;grid-template-columns:repeat(4,1fr) auto;gap:8px}.school-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:16px}.school-card{border:1px solid #cbd5e1;border-radius:14px;padding:18px}.school-card.inactive{opacity:.7;border-style:dashed}.school-card h3{margin:0}.status{padding:4px 9px;border-radius:999px;background:#dcfce7;color:#166534;font-size:12px;font-weight:800}.inactive .status{background:#fee2e2;color:#991b1b}.meta{color:#64748b;font-size:13px;margin:8px 0 14px}.edit-grid{display:grid;grid-template-columns:1fr 2fr;gap:8px}.password-row{display:flex;gap:8px;margin-top:10px}.password-row input{flex:1}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.message{min-height:22px;font-weight:700}.version{position:fixed;right:12px;bottom:10px;color:#64748b;font-weight:bold}@media(max-width:760px){.create,.edit-grid{grid-template-columns:1fr}.password-row{flex-direction:column}}
</style></head><body><main><h1>Plataforma multi-colegio</h1><p>Administración general de establecimientos, accesos y personalización.</p><p id="msg" class="message"></p>
<section><h2>Crear colegio y administrador inicial</h2><div class="create"><input id="code" placeholder="Código: colegio-norte"><input id="schoolName" placeholder="Nombre del colegio"><input id="user" placeholder="Usuario administrador"><input id="pass" type="password" placeholder="Contraseña segura"><button id="create">Crear colegio</button></div></section>
<section><h2>Colegios registrados</h2><div id="list" class="school-grid"></div></section></main><div class="version">v2.1.0</div><script src="sesion-cliente.js"></script><script>
const msg=document.querySelector('#msg');function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function call(body){const r=await window.simceAuthenticatedFetch('plataforma_api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'No se pudo completar la operación.');return x}function status(text,ok=true){msg.textContent=text;msg.style.color=ok?'#166534':'#b91c1c'}
async function load(){const r=await window.simceAuthenticatedFetch('plataforma_api.php'),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'No se pudo cargar la lista.');list.innerHTML=x.colegios.map(c=>'<article class="school-card '+(Number(c.activo)===1?'':'inactive')+'"><div style="display:flex;justify-content:space-between;gap:10px"><h3>'+esc(c.nombre)+'</h3><span class="status">'+(Number(c.activo)===1?'Activo':'Desactivado')+'</span></div><div class="meta">Administrador: <strong>'+esc(c.admin_usuario||'Sin administrador')+'</strong> · '+esc(c.usuarios)+' usuario(s) · '+esc(c.alumnos)+' estudiante(s)</div><div class="edit-grid"><input id="code-'+c.id+'" value="'+esc(c.codigo)+'" aria-label="Código"><input id="name-'+c.id+'" value="'+esc(c.nombre)+'" aria-label="Nombre del colegio"></div><div class="password-row"><input id="password-'+c.id+'" type="password" placeholder="Nueva contraseña del administrador"><button onclick="resetPassword('+c.id+')">Restablecer contraseña</button></div><div class="actions"><button onclick="editSchool('+c.id+')">Guardar datos</button><a class="action secondary" href="estudiantes.php?colegio='+encodeURIComponent(c.codigo)+'">👥 Estudiantes</a><a class="action secondary" href="personalizacion_v21.php?colegio='+encodeURIComponent(c.codigo)+'">🎨 Personalización</a><button class="'+(Number(c.activo)===1?'secondary':'success')+'" onclick="toggleSchool('+c.id+','+(Number(c.activo)===1?0:1)+')">'+(Number(c.activo)===1?'Desactivar':'Activar')+'</button><button class="danger" onclick="deleteSchool('+c.id+','+JSON.stringify(c.codigo)+')">Eliminar</button></div></article>').join('')}
create.onclick=async()=>{try{await call({action:'create_school',codigo:code.value,nombre:schoolName.value,usuario:user.value,password:pass.value});status('Colegio creado.');code.value=schoolName.value=user.value=pass.value='';await load()}catch(e){status(e.message,false)}};
async function editSchool(id){try{await call({action:'edit_school',id,codigo:document.querySelector('#code-'+id).value,nombre:document.querySelector('#name-'+id).value});status('Datos del colegio actualizados.');await load()}catch(e){status(e.message,false)}}
async function resetPassword(id){const input=document.querySelector('#password-'+id);if(!input.value)return status('Escribe la nueva contraseña.',false);if(!confirm('¿Restablecer la contraseña del administrador de este colegio?'))return;try{await call({action:'reset_school_password',id,password:input.value});input.value='';status('Contraseña restablecida y cuenta activada.')}catch(e){status(e.message,false)}}
async function toggleSchool(id,activo){if(!confirm('¿'+(activo?'Activar':'Desactivar')+' este colegio?'))return;try{await call({action:'toggle_school',id,activo});status(activo?'Colegio activado.':'Colegio desactivado.');await load()}catch(e){status(e.message,false)}}
async function deleteSchool(id,code){const confirmation=prompt('Esta acción eliminará permanentemente el colegio y todos sus datos. Escribe el código "'+code+'" para continuar.');if(confirmation===null)return;try{await call({action:'delete_school',id,confirmation});status('Colegio eliminado permanentemente.');await load()}catch(e){status(e.message,false)}}
load().catch(e=>status(e.message,false));
</script></body></html>
