<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php';simceRequireRole(array('plataforma_superadmin'));$db=simceDatabase();
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){$rows=$db->query("SELECT c.id,c.codigo,c.nombre,c.activo,c.created_at,(SELECT COUNT(*) FROM administradores u WHERE u.colegio_id=c.id) usuarios,(SELECT COUNT(*) FROM alumnos a WHERE a.colegio_id=c.id) alumnos FROM colegios c ORDER BY c.nombre")->fetchAll();simceJson(array('ok'=>true,'colegios'=>$rows,'version'=>SIMCE_VERSION));}
simceRequireCsrf();$d=simceReadJson(65536);$action=(string)($d['action']??'');
if($action==='create_school'){$code=strtolower(trim((string)($d['codigo']??'')));$name=trim((string)($d['nombre']??''));$user=trim((string)($d['usuario']??''));$pass=(string)($d['password']??'');if(!preg_match('/^[a-z0-9-]{3,40}$/',$code)||$name===''||!preg_match('/^[A-Za-z0-9._-]{3,50}$/',$user)||strlen($pass)<12||!preg_match('/[A-Z]/',$pass)||!preg_match('/[a-z]/',$pass)||!preg_match('/[0-9]/',$pass))simceJson(array('ok'=>false,'error'=>'Revisa código, nombre, usuario y contraseña segura.'),400);try{$db->beginTransaction();$s=$db->prepare('INSERT INTO colegios(codigo,nombre)VALUES(:c,:n)');$s->execute(array(':c'=>$code,':n'=>$name));$cid=(int)$db->lastInsertId();$u=$db->prepare("INSERT INTO administradores(colegio_id,usuario,password_hash,rol)VALUES(:c,:u,:p,'colegio_admin')");$u->execute(array(':c'=>$cid,':u'=>$user,':p'=>password_hash($pass,PASSWORD_DEFAULT)));$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();simceJson(array('ok'=>false,'error'=>'El código del colegio ya existe o no pudo crearse.'),409);}simceJson(array('ok'=>true));}
if($action==='toggle_school'){$id=(int)($d['id']??0);$active=!empty($d['activo'])?1:0;$s=$db->prepare('UPDATE colegios SET activo=:a WHERE id=:id');$s->execute(array(':a'=>$active,':id'=>$id));simceJson(array('ok'=>true));}
simceJson(array('ok'=>false,'error'=>'Acción no válida.'),400);

