<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php';
require_once __DIR__.'/politica_pruebas.php';
simceSecurityHeaders();$db=simceDatabase();$method=$_SERVER['REQUEST_METHOD']??'GET';$action=(string)($_GET['action']??'courses');
if($method==='GET'&&$action==='schools'){$s=$db->query('SELECT codigo,nombre FROM colegios WHERE activo=1 ORDER BY nombre');simceJson(array('ok'=>true,'colegios'=>$s->fetchAll()));}
if($method==='GET'&&$action==='courses'){$school=simceSchoolByCode($db,(string)($_GET['colegio']??''));if(!$school)simceJson(array('ok'=>false,'error'=>'Codigo de colegio no valido.'),404);simceSyncCourses($db,(int)$school['id']);$s=$db->prepare('SELECT id,nombre FROM cursos WHERE colegio_id=:c AND activo=1 ORDER BY idgrado,nombre');$s->execute(array(':c'=>$school['id']));simceJson(array('ok'=>true,'colegio'=>$school['nombre'],'usa_lista_estudiantes'=>simceStudentListsEnabled($db,(int)$school['id']),'cursos'=>$s->fetchAll()));}
if($method==='GET'&&$action==='students'){$school=simceSchoolByCode($db,(string)($_GET['colegio']??''));if(!$school)simceJson(array('ok'=>false,'error'=>'Codigo de colegio no valido.'),404);if(!simceStudentListsEnabled($db,(int)$school['id']))simceJson(array('ok'=>false,'error'=>'El ingreso mediante lista está desactivado.'),409);$s=$db->prepare('SELECT a.public_id,a.nombre FROM alumnos a JOIN cursos c ON c.nombre=a.curso AND c.colegio_id=a.colegio_id WHERE c.id=:course AND a.colegio_id=:school AND a.activo=1 AND c.activo=1 ORDER BY a.nombre');$s->execute(array(':course'=>(int)($_GET['curso']??0),':school'=>$school['id']));simceJson(array('ok'=>true,'estudiantes'=>$s->fetchAll()));}
if($method==='GET'&&$action==='session'){simceStartStudentSession();if(empty($_SESSION['alumno_id']))simceJson(array('ok'=>true,'authenticated'=>false));$student=simceRequireStudent();simceSyncStoredTests($db,(int)$student['colegio_id']);$s=$db->prepare('SELECT p.id,p.titulo,p.asignatura FROM asignaciones a JOIN pruebas p ON p.id=a.prueba_id AND p.colegio_id=a.colegio_id WHERE a.curso_id=:c AND a.colegio_id=:school AND a.activa=1 AND p.activa=1 ORDER BY p.asignatura,p.titulo');$s->execute(array(':c'=>$student['curso_id'],':school'=>$student['colegio_id']));$tests=$s->fetchAll();foreach($tests as&$test){$configured=simceTestPolicy($db,(int)$student['curso_id'],(int)$test['id'],(int)$student['colegio_id']);$test['intentos_usados']=simceAttemptCount($db,$student,(int)$test['id']);$test['intentos_maximos']=$configured?$configured['policy']['attempts']:0;$test['agotada']=!$configured||($test['intentos_maximos']>0&&$test['intentos_usados']>=$test['intentos_maximos']);}unset($test);simceJson(array('ok'=>true,'authenticated'=>true,'acceso_libre'=>!empty($student['acceso_libre']),'estudiante'=>array('nombre'=>$student['nombre'],'curso'=>$student['curso']),'pruebas'=>$tests));}
if($method!=='POST')simceJson(array('ok'=>false,'error'=>'Solicitud no valida.'),405);$d=simceReadJson(65536);if(($d['action']??'login')==='logout'){simceStartStudentSession();$_SESSION=array();session_destroy();simceJson(array('ok'=>true));}
$school=simceSchoolByCode($db,(string)($d['colegio']??''));if(!$school)simceJson(array('ok'=>false,'error'=>'Codigo de colegio no valido.'),401);$usesList=simceStudentListsEnabled($db,(int)$school['id']);$courseId=(int)($d['curso']??0);$pin=(string)($d['pin']??'');$course=$db->prepare('SELECT id,nombre,pin_hash,requiere_pin FROM cursos WHERE id=:course AND colegio_id=:school AND activo=1');$course->execute(array(':course'=>$courseId,':school'=>$school['id']));$courseRow=$course->fetch();if(!$courseRow)simceJson(array('ok'=>false,'error'=>'Selecciona un curso valido.'),400);if((int)$courseRow['requiere_pin']===1&&(empty($courseRow['pin_hash'])||!password_verify($pin,$courseRow['pin_hash'])))simceJson(array('ok'=>false,'error'=>'PIN incorrecto.'),401);if($usesList){$s=$db->prepare('SELECT a.id,a.nombre,a.curso,a.colegio_id,c.id curso_id FROM alumnos a JOIN cursos c ON c.nombre=a.curso AND c.colegio_id=a.colegio_id WHERE a.public_id=:p AND c.id=:course AND a.colegio_id=:school AND a.activo=1 AND c.activo=1');$s->execute(array(':p'=>(string)($d['estudiante']??''),':course'=>$courseId,':school'=>$school['id']));$student=$s->fetch();if(!$student)simceJson(array('ok'=>false,'error'=>'Estudiante no encontrado.'),401);$studentId=(int)$student['id'];$studentName='';}else{$studentName=preg_replace('/\s+/u',' ',trim((string)($d['nombre']??'')))??'';$nameLength=function_exists('mb_strlen')?mb_strlen($studentName,'UTF-8'):strlen($studentName);if($nameLength<2||$nameLength>150||preg_match('/[\x00-\x1F\x7F]/u',$studentName))simceJson(array('ok'=>false,'error'=>'Escribe un nombre valido de entre 2 y 150 caracteres.'),400);$studentId=-random_int(1,2147483647);}simceStartStudentSession();session_regenerate_id(true);$_SESSION['alumno_id']=$studentId;$_SESSION['curso_id']=$courseId;$_SESSION['colegio_id']=(int)$school['id'];$_SESSION['last_activity']=time();if($usesList)unset($_SESSION['alumno_nombre_libre']);else $_SESSION['alumno_nombre_libre']=$studentName;simceJson(array('ok'=>true));
