<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php';simceSecurityHeaders();$db=simceDatabase();$method=$_SERVER['REQUEST_METHOD']??'GET';$action=(string)($_GET['action']??'courses');
if($method==='GET'&&$action==='schools'){$s=$db->query('SELECT codigo,nombre FROM colegios WHERE activo=1 ORDER BY nombre');simceJson(array('ok'=>true,'colegios'=>$s->fetchAll()));}
if($method==='GET'&&$action==='courses'){$school=simceSchoolByCode($db,(string)($_GET['colegio']??''));if(!$school)simceJson(array('ok'=>false,'error'=>'Código de colegio no válido.'),404);simceSyncCourses($db,(int)$school['id']);$s=$db->prepare('SELECT id,nombre FROM cursos WHERE colegio_id=:c AND activo=1 ORDER BY idgrado,nombre');$s->execute(array(':c'=>$school['id']));simceJson(array('ok'=>true,'colegio'=>$school['nombre'],'cursos'=>$s->fetchAll()));}
if($method==='GET'&&$action==='students'){$school=simceSchoolByCode($db,(string)($_GET['colegio']??''));if(!$school)simceJson(array('ok'=>false,'error'=>'Código de colegio no válido.'),404);$s=$db->prepare('SELECT a.public_id,a.nombre FROM alumnos a JOIN cursos c ON c.nombre=a.curso AND c.colegio_id=a.colegio_id WHERE c.id=:course AND a.colegio_id=:school AND a.activo=1 AND c.activo=1 ORDER BY a.nombre');$s->execute(array(':course'=>(int)($_GET['curso']??0),':school'=>$school['id']));simceJson(array('ok'=>true,'estudiantes'=>$s->fetchAll()));}
if($method==='GET'&&$action==='session'){simceStartStudentSession();if(empty($_SESSION['alumno_id']))simceJson(array('ok'=>true,'authenticated'=>false));$student=simceRequireStudent();simceSyncStoredTests($db,(int)$student['colegio_id']);$s=$db->prepare('SELECT p.id,p.titulo,p.asignatura FROM asignaciones a JOIN pruebas p ON p.id=a.prueba_id AND p.colegio_id=a.colegio_id WHERE a.curso_id=:c AND a.colegio_id=:school AND a.activa=1 AND p.activa=1 ORDER BY p.asignatura,p.titulo');$s->execute(array(':c'=>$student['curso_id'],':school'=>$student['colegio_id']));simceJson(array('ok'=>true,'authenticated'=>true,'estudiante'=>array('nombre'=>$student['nombre'],'curso'=>$student['curso']),'pruebas'=>$s->fetchAll()));}
if($method!=='POST')simceJson(array('ok'=>false,'error'=>'Solicitud no válida.'),405);$d=simceReadJson(65536);if(($d['action']??'login')==='logout'){simceStartStudentSession();$_SESSION=array();session_destroy();simceJson(array('ok'=>true));}
$school=simceSchoolByCode($db,(string)($d['colegio']??''));if(!$school)simceJson(array('ok'=>false,'error'=>'Código de colegio no válido.'),401);$s=$db->prepare('SELECT a.id,a.nombre,a.curso,a.colegio_id,c.id curso_id,c.pin_hash,c.requiere_pin FROM alumnos a JOIN cursos c ON c.nombre=a.curso AND c.colegio_id=a.colegio_id WHERE a.public_id=:p AND c.id=:course AND a.colegio_id=:school AND a.activo=1 AND c.activo=1');$s->execute(array(':p'=>(string)($d['estudiante']??''),':course'=>(int)($d['curso']??0),':school'=>$school['id']));$student=$s->fetch();if(!$student)simceJson(array('ok'=>false,'error'=>'Estudiante no encontrado.'),401);if((int)$student['requiere_pin']===1&&(empty($student['pin_hash'])||!password_verify((string)($d['pin']??''),$student['pin_hash'])))simceJson(array('ok'=>false,'error'=>'PIN incorrecto.'),401);simceStartStudentSession();session_regenerate_id(true);$_SESSION['alumno_id']=(int)$student['id'];$_SESSION['curso_id']=(int)$student['curso_id'];$_SESSION['colegio_id']=(int)$school['id'];$_SESSION['last_activity']=time();simceJson(array('ok'=>true));
