<?php require_once __DIR__.'/seguridad.php';simceRequireRole(array('colegio_admin','docente'),false);?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard de resultados</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f1f5f9;color:#172554;font-family:Inter,Arial,sans-serif}main{max-width:1240px;margin:auto;padding:24px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:22px}.back{display:inline-flex;align-items:center;gap:8px;padding:10px 14px;border-radius:9px;background:#e2e8f0;color:#1e293b;text-decoration:none;font-weight:700}.title h1{margin:0 0 5px}.title p{margin:0;color:#64748b}.filters,.kpis,.courses{display:grid;gap:14px}.filters{grid-template-columns:repeat(3,minmax(180px,1fr));background:#fff;padding:16px;border-radius:14px;margin-bottom:16px}.filters label{font-size:13px;font-weight:700;color:#475569}.filters select,.filters input{display:block;width:100%;margin-top:6px;padding:11px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.kpis{grid-template-columns:repeat(4,1fr);margin-bottom:18px}.kpi,.course-card{background:#fff;border-radius:14px;padding:18px;border:1px solid #e2e8f0}.kpi span{display:block;color:#64748b;font-size:13px;font-weight:700}.kpi strong{display:block;font-size:28px;margin-top:8px}.courses{grid-template-columns:repeat(auto-fit,minmax(205px,1fr));margin-bottom:18px}.course-card h3{margin:0 0 12px}.course-card div{display:flex;justify-content:space-between;margin-top:7px;color:#475569}.panel{background:#fff;border-radius:14px;padding:18px;overflow:auto}.panel h2{margin-top:0}table{width:100%;border-collapse:collapse;min-width:780px}th,td{text-align:left;padding:11px;border-bottom:1px solid #e2e8f0}th{font-size:12px;text-transform:uppercase;color:#64748b}.score{font-weight:800}.good{color:#15803d}.low{color:#b91c1c}.empty{text-align:center;color:#64748b;padding:35px}@media(max-width:760px){.filters,.kpis{grid-template-columns:1fr 1fr}.top{align-items:flex-start}}@media(max-width:480px){.filters,.kpis{grid-template-columns:1fr}}
</style></head><body><main>
<div class="top"><a class="back" href="pruebas_educativas.php">← Panel docente</a><div class="title"><h1>📊 Resultados de evaluaciones</h1><p id="subtitle">Resumen del colegio por curso y prueba</p></div><div data-simce-identity></div></div>
<section class="filters"><label>Curso<select id="courseFilter"><option value="">Todos los cursos</option></select></label><label>Asignatura<select id="subjectFilter"><option value="">Todas las asignaturas</option></select></label><label>Buscar estudiante o prueba<input id="search" type="search" placeholder="Escribe para buscar…"></label></section>
<section class="kpis"><article class="kpi"><span>Intentos registrados</span><strong id="attempts">0</strong></article><article class="kpi"><span>Estudiantes evaluados</span><strong id="students">0</strong></article><article class="kpi"><span>Promedio general</span><strong id="average">—</strong></article><article class="kpi"><span>Logro ≥ 60%</span><strong id="passRate">—</strong></article></section>
<section><h2>Resumen por curso</h2><div id="courseCards" class="courses"></div></section>
<section class="panel"><h2>Detalle de resultados</h2><table><thead><tr><th>Curso</th><th>Estudiante</th><th>Asignatura</th><th>Prueba</th><th>Intento</th><th>Resultado</th><th>Nota</th><th>Fecha</th></tr></thead><tbody id="resultRows"></tbody></table><div id="empty" class="empty" hidden>No hay resultados para los filtros seleccionados.</div></section>
</main><script src="sesion-cliente.js"></script><script>
let allResults=[];const collator=new Intl.Collator('es',{numeric:true,sensitivity:'base'});const courseFilter=document.querySelector('#courseFilter'),subjectFilter=document.querySelector('#subjectFilter'),search=document.querySelector('#search'),attempts=document.querySelector('#attempts'),students=document.querySelector('#students'),average=document.querySelector('#average'),passRate=document.querySelector('#passRate'),courseCards=document.querySelector('#courseCards'),resultRows=document.querySelector('#resultRows'),empty=document.querySelector('#empty'),subtitle=document.querySelector('#subtitle'),resultsTable=document.querySelector('table');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function unique(values){return [...new Set(values.filter(Boolean))].sort(collator.compare)}
function filtered(){const term=search.value.trim().toLocaleLowerCase('es');return allResults.filter(r=>(!courseFilter.value||r.curso===courseFilter.value)&&(!subjectFilter.value||r.asignatura===subjectFilter.value)&&(!term||(r.nombre+' '+r.titulo+' '+r.asignatura).toLocaleLowerCase('es').includes(term)))}
function fillSelect(select,values,label){const current=select.value;select.innerHTML='<option value="">'+label+'</option>'+values.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');select.value=values.includes(current)?current:''}
function render(){const rows=filtered().sort((a,b)=>collator.compare(a.curso,b.curso)||collator.compare(a.asignatura,b.asignatura)||collator.compare(a.titulo,b.titulo)||collator.compare(a.nombre,b.nombre));const percentages=rows.map(r=>Number(r.porcentaje)||0);attempts.textContent=rows.length;students.textContent=new Set(rows.map(r=>r.nombre+'|'+r.curso)).size;average.textContent=rows.length?(percentages.reduce((a,b)=>a+b,0)/rows.length).toFixed(1)+'%':'—';passRate.textContent=rows.length?Math.round(percentages.filter(v=>v>=60).length*100/rows.length)+'%':'—';const groups={};rows.forEach(r=>{(groups[r.curso]??=[]).push(r)});courseCards.innerHTML=Object.keys(groups).sort(collator.compare).map(course=>{const values=groups[course].map(r=>Number(r.porcentaje)||0),avg=values.reduce((a,b)=>a+b,0)/values.length;return '<article class="course-card"><h3>'+esc(course)+'</h3><div><span>Intentos</span><strong>'+values.length+'</strong></div><div><span>Promedio</span><strong>'+avg.toFixed(1)+'%</strong></div><div><span>Estudiantes</span><strong>'+new Set(groups[course].map(r=>r.nombre)).size+'</strong></div></article>'}).join('');resultRows.innerHTML=rows.map(r=>'<tr><td>'+esc(r.curso)+'</td><td>'+esc(r.nombre)+'</td><td>'+esc(r.asignatura)+'</td><td>'+esc(r.titulo)+'</td><td>'+esc(r.intento)+'</td><td class="score '+(Number(r.porcentaje)>=60?'good':'low')+'">'+esc(r.correctas)+'/'+esc(r.total)+' ('+esc(r.porcentaje)+'%)</td><td>'+esc(r.nota||'—')+'</td><td>'+esc(r.finalizado_at||'—')+'</td></tr>').join('');empty.hidden=rows.length>0;resultsTable.hidden=rows.length===0}
async function load(){const response=await window.simceAuthenticatedFetch('gestion_v21_api.php'),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'No se pudieron cargar los resultados.');subtitle.textContent='Resultados — '+data.colegio.nombre;allResults=data.resultados||[];fillSelect(courseFilter,unique(allResults.map(r=>r.curso)),'Todos los cursos');fillSelect(subjectFilter,unique(allResults.map(r=>r.asignatura)),'Todas las asignaturas');render()}
[courseFilter,subjectFilter].forEach(el=>el.addEventListener('change',render));search.addEventListener('input',render);load().catch(e=>{empty.hidden=false;empty.textContent=e.message});
</script><script src="marca.js"></script></body></html>
