<?php
declare(strict_types=1);
require_once __DIR__.'/seguridad.php'; simceSecurityHeaders(); $db=simceDatabase();
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET')simceJson(array('ok'=>true,'marca'=>simceBranding($db)));
simceRequireRole(array('superadmin','administrador')); simceRequireCsrf();
$fields=array('nombre_plataforma'=>80,'nombre_establecimiento'=>120,'subtitulo'=>120,'saludo'=>120,'seleccion_perfil'=>100);
foreach($fields as $key=>$max){$value=trim((string)($_POST[$key]??''));if($value===''||(function_exists('mb_strlen')?mb_strlen($value,'UTF-8'):strlen($value))>$max)simceJson(array('ok'=>false,'error'=>'Revisa el campo '.$key.'.'),400);$s=$db->prepare('SELECT clave FROM configuracion WHERE clave=:k');$s->execute(array(':k'=>'marca_'.$key));if($s->fetch()){$q=$db->prepare('UPDATE configuracion SET valor=:v,updated_at=CURRENT_TIMESTAMP WHERE clave=:k');}else{$q=$db->prepare('INSERT INTO configuracion(clave,valor) VALUES(:k,:v)');}$q->execute(array(':k'=>'marca_'.$key,':v'=>$value));}
if(isset($_FILES['logo'])&&($_FILES['logo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$f=$_FILES['logo'];if(($f['error']??1)!==UPLOAD_ERR_OK||($f['size']??0)>2097152)simceJson(array('ok'=>false,'error'=>'El logo no pudo subirse o supera 2 MB.'),400);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allowed=array('image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp','image/svg+xml'=>'svg');if(!isset($allowed[$mime]))simceJson(array('ok'=>false,'error'=>'Usa un logo PNG, JPG, WebP o SVG.'),400);$dir=__DIR__.'/uploads/marca';if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))simceJson(array('ok'=>false,'error'=>'No se pudo crear la carpeta del logo.'),500);$relative='uploads/marca/logo.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],__DIR__.'/'.$relative))simceJson(array('ok'=>false,'error'=>'No se pudo guardar el logo.'),500);foreach(glob($dir.'/logo.*')?:array() as $old)if(realpath($old)!==realpath(__DIR__.'/'.$relative))@unlink($old);$s=$db->prepare('SELECT clave FROM configuracion WHERE clave=:k');$s->execute(array(':k'=>'marca_logo'));$q=$s->fetch()?$db->prepare('UPDATE configuracion SET valor=:v,updated_at=CURRENT_TIMESTAMP WHERE clave=:k'):$db->prepare('INSERT INTO configuracion(clave,valor) VALUES(:k,:v)');$q->execute(array(':k'=>'marca_logo',':v'=>$relative));}
simceJson(array('ok'=>true,'marca'=>simceBranding($db)));
