<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Acceso de estudiantes</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#eef2ff;color:#172554;padding:24px}.card{max-width:700px;margin:5vh auto;background:#fff;border-radius:20px;padding:28px;box-shadow:0 18px 50px #1e3a8a22}h1{margin:0 0 8px}label{display:block;font-weight:700;margin:18px 0 6px}select,input,button{width:100%;padding:13px;border:1px solid #94a3b8;border-radius:10px;font-size:16px}button{margin-top:20px;background:#1d4ed8;color:#fff;border:0;font-weight:800;cursor:pointer}.error{color:#b91c1c;margin-top:12px}.test{display:block;padding:15px;margin:12px 0;border:1px solid #bfdbfe;border-radius:12px;text-decoration:none;color:#1e3a8a;background:#eff6ff;font-weight:700}.muted{color:#64748b}.hidden{display:none}.logout{background:#475569;width:auto;padding:9px 15px;float:right}
</style></head><body><main class="card"><button id="logout" class="logout hidden">Salir</button><h1>Pruebas de estudiantes</h1><p class="muted">Selecciona tu curso y tu nombre. Tu profesor te entregará el PIN común del curso.</p>
<section id="login"><label>Curso</label><select id="curso"><option value="">Selecciona un curso</option></select><label>Estudiante</label><select id="estudiante" disabled><option>Primero selecciona el curso</option></select><label>PIN del curso</label><input id="pin" type="password" inputmode="numeric" autocomplete="one-time-code" maxlength="30"><button id="enter">Ingresar a mis pruebas</button><div id="error" class="error"></div></section>
<section id="panel" class="hidden"><h2 id="welcome"></h2><p class="muted">Las respuestas y resultados quedarán asociados automáticamente a tu nombre.</p><div id="tests"></div></section></main><script>
const api='portal_estudiante_api.php',curso=document.querySelector('#curso'),student=document.querySelector('#estudiante'),error=document.querySelector('#error');
async function json(url,opt){const r=await fetch(url,opt);return r.json()} async function courses(){const x=await json(api+'?action=courses');x.cursos.forEach(c=>curso.add(new Option(c.nombre,c.id)))}
curso.onchange=async()=>{student.innerHTML='<option value="">Selecciona tu nombre</option>';student.disabled=!curso.value;if(!curso.value)return;const x=await json(api+'?action=students&curso='+encodeURIComponent(curso.value));x.estudiantes.forEach(s=>student.add(new Option(s.nombre,s.public_id)))};
document.querySelector('#enter').onclick=async()=>{error.textContent='';if(!curso.value||!student.value){error.textContent='Selecciona el curso y el estudiante.';return}const x=await json(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',curso:curso.value,estudiante:student.value,pin:document.querySelector('#pin').value})});if(!x.ok){error.textContent=x.error;return}session()};
async function session(){const x=await json(api+'?action=session');if(!x.authenticated)return;document.querySelector('#login').classList.add('hidden');document.querySelector('#panel').classList.remove('hidden');document.querySelector('#logout').classList.remove('hidden');document.querySelector('#welcome').textContent=x.estudiante.nombre+' — '+x.estudiante.curso;document.querySelector('#tests').innerHTML=x.pruebas.length?x.pruebas.map(p=>`<a class="test" href="rendir_prueba.php?id=${p.id}">${p.asignatura}: ${p.titulo}</a>`).join(''):'<p>No hay pruebas asignadas por ahora.</p>'}
document.querySelector('#logout').onclick=async()=>{await json(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.reload()};courses().then(session);
</script></body></html>
